title: Alexandre Lalance
description: Machine learning, quantitative research, aerospace ML and optimization portfolio.
url: https://drivax.github.io
baseurl: ""
markdown: kramdown
permalink: pretty
exclude:
	- README.md
	- .vscode/
